name: ego
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter


  ################################ Notifications ###################################################
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  onesignal_flutter: ^5.0.2
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  rxdart: ^0.27.7
  path_provider: ^2.1.1

  ##################################################################################################
  ##################################################################################################
  ##################################################################################################
  ##################################################################################################



  cupertino_icons: ^1.0.8
  qr_flutter: ^4.0.0
  mobile_scanner: ^3.5.4
  envied: ^1.1.1
  gap: ^3.0.1
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  persistent_bottom_nav_bar_v2: ^6.0.0
  flutter_bloc: ^9.0.0
  password_strength_indicator: ^1.0.1
  flutter_holo_date_picker: ^2.0.0
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  dio_adapter: ^1.9.0
  encrypt: ^5.0.3
  logger: ^2.5.0
  dio: ^5.8.0+1
  fpdart: ^1.1.1
  freezed:
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  dartz : ^0.10.1
  flutter_libphonenumber: ^2.5.1
  google_fonts:
  phone_number:
  intl_phone_field :
  retry:
  bloc: ^9.0.0
  flutter_conditional_rendering: ^2.1.0
  signalr_netcore: ^1.4.1
  sqflite: ^2.4.0
  syncfusion_flutter_charts: ^28.2.7
  flutter_inappwebview: ^6.1.5
  file_picker: ^9.2.1
  flutter_slidable: ^4.0.0
  pinput: ^5.0.1
  local_auth: ^2.3.0
  url_launcher: ^6.3.1
  app_settings: ^6.1.1
  percent_indicator: ^4.2.4
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1
  auto_animated: ^3.0.0
  flutter_svg: ^2.0.7
  equatable: ^2.0.5
  easy_localization: ^3.0.1
  pretty_dio_logger: ^1.3.1
  event_bus: ^2.0.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_native_splash:
  audioplayers: ^5.2.1
  lottie:
  country_pickers:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  pub_semver: ^2.2.0
  package_info_plus: ^8.3.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"         # أو صورة: "assets/images/bg.png"
  adaptive_icon_foreground: "assets/images/logo.png"


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/langs/
    - assets/images/
    - assets/audio/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
    - family: Messi
      fonts:
        - asset: assets/fonts/Messi/ElMessiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/Messi/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/Messi/ElMessiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/Messi/ElMessiri-SemiBold.ttf
          weight: 600
    - family: Edu
      fonts:
        - asset: assets/fonts/Edu/EduAUVICWANTArrows-Bold.ttf
          weight: 700
        - asset: assets/fonts/Edu/EduAUVICWANTArrows-Medium.ttf
          weight: 500
        - asset: assets/fonts/Edu/EduAUVICWANTArrows-Regular.ttf
          weight: 400
        - asset: assets/fonts/Edu/EduAUVICWANTArrows-SemiBold.ttf
          weight: 600

    #    - family: Abel
    #      fonts:
    #        - asset: assets/fonts/fira/FiraSans-Thin.ttf
    #          weight: 100
    #        - asset: assets/fonts/fira/FiraSans-ThinItalic.ttf
    #          weight: 100
    #          style: italic
    #        - asset: assets/fonts/fira/FiraSans-ExtraLight.ttf
    #          weight: 200
    #        - asset: assets/fonts/fira/FiraSans-ExtraLightItalic.ttf
    #          weight: 200
    #          style: italic
    #        - asset: assets/fonts/fira/FiraSans-Light.ttf
    #          weight: 300
    #        - asset: assets/fonts/fira/FiraSans-LightItalic.ttf
    #          weight: 300
    #          style: italic
    #        - asset: assets/fonts/fira/FiraSans-Regular.ttf
    #          weight: 400
    #        - asset: assets/fonts/fira/FiraSans-Italic.ttf
    #          weight: 400
    #          style: italic
    #        - asset: assets/fonts/fira/FiraSans-Medium.ttf
    #          weight: 500
    #        - asset: assets/fonts/fira/FiraSans-MediumItalic.ttf
    #          weight: 500
    #          style: italic
    #        - asset: assets/fonts/fira/FiraSans-SemiBold.ttf
    #          weight: 600
    #        - asset: assets/fonts/fira/FiraSans-SemiBoldItalic.ttf
    #          weight: 600
    #          style: italic
    #        - asset: assets/fonts/fira/FiraSans-Bold.ttf
    #          weight: 700
    #        - asset: assets/fonts/fira/FiraSans-BoldItalic.ttf
    #          weight: 700
    #          style: italic
    #        - asset: assets/fonts/fira/FiraSans-ExtraBold.ttf
    #          weight: 800
    #        - asset: assets/fonts/fira/FiraSans-ExtraBoldItalic.ttf
    #          weight: 800
    #          style: italic
    #        - asset: assets/fonts/fira/FiraSans-Black.ttf
    #          weight: 900
    #        - asset: assets/fonts/fira/FiraSans-BlackItalic.ttf
    #          weight: 900
    #          style: italic
    - family: Mono
      fonts:
        - asset: assets/fonts/mono/DMMono-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/mono/DMMono-Light.ttf
          weight: 300
        - asset: assets/fonts/mono/DMMono-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/mono/DMMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/mono/DMMono-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/mono/DMMono-Regular.ttf
          weight: 400

#    - family: Abel
#      fonts:
#        - asset: assets/fonts/osw/Oswald-VariableFont_wght.ttf
