// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjpx9sEG9KI6YQyiHapvbQSXN6FlDT3Sk',
    appId: '1:218905853651:android:4ca2ce3963cc8b35b39e26',
    messagingSenderId: '218905853651',
    projectId: 'ego-6ceed',
    storageBucket: 'ego-6ceed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtlwYFBSfvDi23YnUbYbUdAJvaTxibk_E',
    appId: '1:218905853651:ios:f494398653c4e035b39e26',
    messagingSenderId: '218905853651',
    projectId: 'ego-6ceed',
    storageBucket: 'ego-6ceed.firebasestorage.app',
    iosBundleId: 'com.example.ego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtlwYFBSfvDi23YnUbYbUdAJvaTxibk_E',
    appId: '1:218905853651:ios:f494398653c4e035b39e26',
    messagingSenderId: '218905853651',
    projectId: 'ego-6ceed',
    storageBucket: 'ego-6ceed.firebasestorage.app',
    iosBundleId: 'com.example.ego',
  );
}
